kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: 4.08.0.bench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make ocaml-versions/4.08.0.bench
- name: 4.07.1.bench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - make ocaml-versions/4.07.1.bench
- name: 4.07.1.parallel_bench
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - export BENCH_TARGET=parallel_bench
  - make ocaml-versions/4.07.1.bench
- name: 4.06.1+multicore.multibench_serial
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - export BENCH_TARGET=multibench_serial
  - make ocaml-versions/4.06.1+multicore.bench
- name: 4.06.1+multicore.multibench_parallel
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install libgmp-dev m4 libdw-dev
  - sudo chown -R opam .
  - export ITER=1
  - export OPAM_DISABLE_SANDBOXING=true
  - export BENCH_TARGET=multibench_parallel
  - make ocaml-versions/4.06.1+multicore.bench

